name: Run UI Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    paths-ignore: [ '**.md' ]
  schedule:
    - cron: ${{ $test_schedule || '30 0 * * *' }}
  workflow_dispatch:


jobs:
  run_ui_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node Packages
        run: npm ci #clean install

      - name: Install Playwright Browser Binaries
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npm run test

      - name: Upload Test Report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test_report
          path: test_report/
          retention-days: 30
